## Connexion with root+pass:  ansible-playbook -i,<IP>  prequisites.yml -u root -k  
### Connexion with root+ssh_key:  ansible-playbook -i,<IP> prequisites.yml -u root
### Only run specific tasks with tags: ansible-playbook -i,<IP> prequisites.yml -u root --tags "<tag>"
---
- hosts: all
  vars:
    ansible_python_interpreter: '{{ ansible_playbook_python }}'
  tasks: 
     - include: tasks/install_pkgs_py3.yml
       tags: [packages]
     - include: tasks/epel.yml
       tags: [packages]
     - include: tasks/disable_selinux_firewall.yml
       tags: [selinux]
     - include: tasks/services.yml   
     - include: tasks/k8s_base.yml 
       tags: [k8s_install]

