---
- name: remove old containers if present ↓↓↓↓ FAILED! is expected here ↓↓↓↓
  command: docker rm --force base-bwapp
  ignore_errors: yes

- name: Pull bwapp base image
  docker_image:
    name: feltsecure/owasp-bwapp
    source: pull

- name: Tag and push to local registry
  docker_image:
    name: feltsecure/owasp-bwapp
    repository: localhost:5000/feltsecure/owasp-bwapp
    push: yes
    source: local

- name: Create a namespace for our stuff
  community.kubernetes.k8s:
    name: waas
    api_version: v1
    kind: Namespace
    state: present

- name: Create a service for bwapp
  community.kubernetes.k8s:
    state: present
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        annotations:
          deployment.kubernetes.io/revision: "1"
        generation: 1
        labels:
          app.kubernetes.io/instance: my-bwapp
          app.kubernetes.io/name: bwapp
          app.kubernetes.io/version: v12.0.2
        name: my-bwapp
        namespace: waas
        selfLink: /apis/apps/v1/namespaces/default/deployments/my-bwapp
      spec:
        progressDeadlineSeconds: 600
        replicas: 1
        revisionHistoryLimit: 10
        selector:
          matchLabels:
            app.kubernetes.io/instance: my-bwapp
            app.kubernetes.io/name: bwapp
        strategy:
          rollingUpdate:
            maxSurge: 25%
            maxUnavailable: 25%
          type: RollingUpdate
        template:
          metadata:
            creationTimestamp: null
            labels:
              app.kubernetes.io/instance: my-bwapp
              app.kubernetes.io/name: bwapp
          spec:
            containers:
            - image: localhost:5000/feltsecure/owasp-bwapp:latest
              imagePullPolicy: IfNotPresent
              livenessProbe:
                failureThreshold: 3
                httpGet:
                  path: /
                  port: http
                  scheme: HTTP
                periodSeconds: 10
                successThreshold: 1
                timeoutSeconds: 1
              name: bwapp
              ports:
              - containerPort: 80
                name: http
                protocol: TCP
              readinessProbe:
                failureThreshold: 3
                httpGet:
                  path: /
                  port: http
                  scheme: HTTP
                periodSeconds: 10
                successThreshold: 1
                timeoutSeconds: 1
              resources: {}
              securityContext: {}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
            dnsPolicy: ClusterFirst
            restartPolicy: Always
            schedulerName: default-scheduler
            securityContext: {}
            terminationGracePeriodSeconds: 30

- name: Create a bwapp service
  community.kubernetes.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        labels:
          app.kubernetes.io/instance: my-bwapp
          app.kubernetes.io/name: bwapp
          app.kubernetes.io/version: v12.0.2
        name: my-bwapp-svc
        namespace: waas
        selfLink: /api/v1/namespaces/default/services/my-bwapp
      spec:
        ports:
        - name: http
          port: 80
          protocol: TCP
          targetPort: http
        selector:
          app.kubernetes.io/instance: my-bwapp
          app.kubernetes.io/name: bwapp
        sessionAffinity: None
        type: ClusterIP

- name: Create a bwapp ingress endpoint
  community.kubernetes.k8s:
    state: present
    definition:
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: bwapp-ing
        namespace: waas
        annotations:
          nginx.ingress.kubernetes.io/rewrite-target: /$2
      spec:
        rules:
        - http:
            paths:
            - path: /bwapp-insecure(/|$)(.*)
              pathType: Prefix
              backend:
                service:
                  name: my-bwapp-svc
                  port:
                    number: 80

