---
- name: Use pip to install Kubespray requirements
  command: "pip3 install -r {{ playbook_dir }}/../kubespray/requirements.txt"

- name: Include vars from k8s.yaml
  include_vars:
    file: k8s.yaml

- name: template single node cluster
  template:
    src: "{{ playbook_dir }}/files/kubespray_inventory_single.ini.j2"
    dest: "{{ playbook_dir }}/../kubespray/inventory/kwaf.ini"
    owner: root
    group: wheel
    mode: 0644
  when: not MultiNodeCluster 

- name: template multi node cluster
  template:
    src: "{{ playbook_dir }}/../kubespray/inventory/kwaf.ini"
    dest: /root/test.conf
    owner: root
    group: wheel
    mode: 0644
  when: MultiNodeCluster

- name: Install Helm - download installer 
  command: "curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3"
  args:
    warn: false

- name: Install Helm - chmod installer
  command: "chmod 700 get_helm.sh"
  args:
    warn: false 

- name: Install Helm - run installer
  command: "./get_helm.sh"

- name: Install Helm - cleanup
  file:
    state: absent
    path: "get_helm.sh"

- name: Configure Helm - add a chart repo "stable"
  command: "helm repo add stable https://charts.helm.sh/stable"

- name: Configure Helm - add a chart repo "securecodebox"
  command: "helm repo add seccurecodebox https://charts.securecodebox.io"

