---

- name: Ajust Kubespray local_volume_provisioner template
  lineinfile:
    path: "{{ playbook_dir }}/../kubespray/roles/kubernetes-apps/external_provisioner/local_volume_provisioner/templates/local-volume-provisioner-sc.yml.j2"
    regexp: 'volumeBindingMode'
    line: 'volumeBindingMode: Immediate'

- name: Creates group_vars directory
  file:
    path: "{{ playbook_dir }}/../kubespray/inventory/group_vars"
    state: directory

- name: Creates group_vars all sub-directory
  file:
    path: "{{ playbook_dir }}/../kubespray/inventory/group_vars/all"
    state: directory

- name: Creates group_vars k8s-cluster sub-directory
  file:
    path: "{{ playbook_dir }}/../kubespray/inventory/group_vars/k8s-cluster"
    state: directory

- name: set group_vars all
  copy:
    src: "{{ item }}"
    dest: "{{ playbook_dir }}/../kubespray/inventory/group_vars/all"
    backup: yes
  with_fileglob:
    - files/group_vars/all/*.yml

- name: set group_vars cluster
  copy:
    src: "{{ item }}"
    dest: "{{ playbook_dir }}/../kubespray/inventory/group_vars/k8s-cluster"
    backup: yes
  with_fileglob:
    - files/group_vars/k8s-cluster/*.yml


