---

- name: Include vars from k8s.yaml
  include_vars:
    file: k8s.yaml

- name: >-
    Patch waas-elasticsearch-deployment statefulset to add node.max_local_storage_nodes value of 10 instead of default (1)
    Otherwise the pods never launch correctly and throw a lock error on the volume
  community.kubernetes.k8s:
    state: present
    definition:
      apiVersion: apps/v1
      kind: StatefulSet
      metadata:
        annotations:
          meta.helm.sh/release-name: waas
          meta.helm.sh/release-namespace: waas
        generation: 4
        labels:
          app.kubernetes.io/instance: WAAS
          app.kubernetes.io/managed-by: Helm
          app.kubernetes.io/name: WAAS
        name: waas-elasticsearch-deployment
        namespace: waas
      spec:
        podManagementPolicy: Parallel
        replicas: 3
        revisionHistoryLimit: 10
        selector:
          matchLabels:
            configid: waas-elasticsearch-container
        serviceName: waas-elasticsearch-service-discovery
        template:
          metadata:
            creationTimestamp: null
            labels:
              app.kubernetes.io/instance: WAAS
              app.kubernetes.io/name: WAAS
              configid: waas-elasticsearch-container
          spec:
            affinity:
              podAntiAffinity:
                preferredDuringSchedulingIgnoredDuringExecution:
                - podAffinityTerm:
                    labelSelector:
                      matchExpressions:
                      - key: component
                        operator: In
                        values:
                        - waas-elasticsearch-container
                    topologyKey: kubernetes.io/hostname
                  weight: 100
            containers:
            - args:
              - -c
              - /usr/local/bin/docker-entrypoint.sh
              command:
              - /bin/bash
              env:
              - name: node.name
                valueFrom:
                  fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.name
              - name: processors
                value: "4"
              - name: indices.lifecycle.poll_interval
                value: 1s
              - name: thread_pool.write.queue_size
                value: "1000"
              - name: thread_pool.write.size
                value: "1"
              - name: indices.memory.index_buffer_size
                value: 50%
              - name: cluster.initial_master_nodes
                value: waas-elasticsearch-deployment-0,waas-elasticsearch-deployment-1,waas-elasticsearch-deployment-2
              - name: discovery.seed_hosts
                value: waas-elasticsearch-service-discovery
              - name: cluster.name
                value: elasticsearch
              - name: network.host
                value: 0.0.0.0
              - name: node.max_local_storage_nodes
                value: "10"
              - name: bootstrap.memory_lock
                value: "true"
              - name: node.store.allow_mmap
                value: "true"
              - name: xpack.security.enabled
                value: "true"
              - name: xpack.security.transport.ssl.enabled
                value: "true"
              - name: xpack.security.transport.ssl.verification_mode
                value: certificate
              - name: xpack.security.transport.ssl.key
                value: /usr/share/elasticsearch/config/esdiscovery/server/tls.key
              - name: xpack.security.transport.ssl.certificate
                value: /usr/share/elasticsearch/config/esdiscovery/server/tls.crt
              - name: xpack.security.transport.ssl.certificate_authorities
                value: /usr/share/elasticsearch/config/esdiscovery/ca/ca.crt
              - name: xpack.security.http.ssl.enabled
                value: "true"
              - name: xpack.security.http.ssl.key
                value: /usr/share/elasticsearch/config/esqueries/server/tls.key
              - name: xpack.security.http.ssl.certificate
                value: /usr/share/elasticsearch/config/esqueries/server/tls.crt
              - name: xpack.security.http.ssl.certificate_authorities
                value: /usr/share/elasticsearch/config/esqueries/ca/ca.crt
              - name: ELASTIC_USER
                valueFrom:
                  secretKeyRef:
                    key: user
                    name: waas-esauth-secret
              - name: ELASTIC_PASSWORD
                valueFrom:
                  secretKeyRef:
                    key: password
                    name: waas-esauth-secret
              - name: KIBANA_SYSTEM_USER
                valueFrom:
                  secretKeyRef:
                    key: user
                    name: waas-ksauth-secret
              - name: KIBANA_SYSTEM_PASSWORD
                valueFrom:
                  secretKeyRef:
                    key: password
                    name: waas-ksauth-secret
              - name: ELASTIC_HEALTH_CHECK_PARAMS
                value: wait_for_status=green&timeout=1s
              image: localhost:5000/waas-elasticsearch:1.4.0
              imagePullPolicy: IfNotPresent
              livenessProbe:
                exec:
                  command:
                  - /probe.sh
                failureThreshold: 10
                initialDelaySeconds: 30
                periodSeconds: 10
                successThreshold: 1
                timeoutSeconds: 6
              name: elasticsearch
              readinessProbe:
                exec:
                  command:
                  - /probe.sh
                failureThreshold: 3
                initialDelaySeconds: 10
                periodSeconds: 10
                successThreshold: 3
                timeoutSeconds: 5
              resources: {}
              securityContext:
                capabilities:
                  add:
                  - IPC_LOCK
                  - SYS_RESOURCE
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              volumeMounts:
              - mountPath: /usr/share/elasticsearch/data
                name: stateful-volume
              - mountPath: /usr/share/elasticsearch/config/esdiscovery/server
                name: esdiscovery-server-volume
              - mountPath: /usr/share/elasticsearch/config/esdiscovery/ca
                name: esdiscovery-ca-volume
              - mountPath: /usr/share/elasticsearch/config/esqueries/server
                name: esqueries-server-volume
              - mountPath: /usr/share/elasticsearch/config/esqueries/ca
                name: esqueries-ca-volume
              - mountPath: /usr/share/elasticsearch/config/jvm.options.d
                name: elasticsearch-jvm-options-volume
              - mountPath: /usr/share/elasticsearch/config/ilm
                name: elasticsearch-ilm-options-volume
            dnsPolicy: ClusterFirst
            initContainers:
            - command:
              - sysctl
              - -w
              - vm.max_map_count=262144
              image: localhost:5000/waas-kubectl:1.4.0
              imagePullPolicy: IfNotPresent
              name: init-sysctl1
              resources: {}
              securityContext:
                privileged: true
                runAsUser: 0
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
            - command:
              - chmod
              - "777"
              - /usr/share/elasticsearch/data
              image: localhost:5000/waas-kubectl:1.4.0
              imagePullPolicy: IfNotPresent
              name: init-sysctl2
              resources: {}
              securityContext:
                privileged: true
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              volumeMounts:
              - mountPath: /usr/share/elasticsearch/data
                name: stateful-volume
            restartPolicy: Always
            schedulerName: default-scheduler
            securityContext: {}
            serviceAccount: waas-elasticsearch-service-account
            serviceAccountName: waas-elasticsearch-service-account
            terminationGracePeriodSeconds: 30
            volumes:
            - configMap:
                defaultMode: 420
                name: waas-elasticsearch-jvm-options-config
              name: elasticsearch-jvm-options-volume
            - configMap:
                defaultMode: 420
                items:
                - key: ilm.options
                  path: ilm.options
                name: waas-elasticsearch-ilm-options-config
              name: elasticsearch-ilm-options-volume
            - configMap:
                defaultMode: 420
                name: waas-esdiscovery-ca-config
              name: esdiscovery-ca-volume
            - name: esdiscovery-server-volume
              secret:
                defaultMode: 420
                secretName: waas-esdiscovery-server-secret
            - configMap:
                defaultMode: 420
                name: waas-esqueries-ca-config
              name: esqueries-ca-volume
            - name: esqueries-server-volume
              secret:
                defaultMode: 420
                secretName: waas-esqueries-server-secret
            - name: stateful-volume
              persistentVolumeClaim:
                claimName: waas-elasticsearch-persistent-volume-claim
        updateStrategy:
          rollingUpdate:
            partition: 0
          type: RollingUpdate
      
- name: install license in waas-licenses-configmap
  community.kubernetes.k8s:
    state: present
    definition:
      apiVersion: v1
      data:
        customer-kwaf-pods-add-1000-13apr2020-19may2021-tgGOzvBU: ""
      kind: ConfigMap
      metadata:
        annotations:
          meta.helm.sh/release-name: waas
          meta.helm.sh/release-namespace: waas
        labels:
          app.kubernetes.io/instance: WAAS
          app.kubernetes.io/managed-by: Helm
          app.kubernetes.io/name: WAAS
        name: waas-licenses-configmap
        namespace: waas
 
