apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "4"
    meta.helm.sh/release-name: my-juice-shop
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2020-12-29T14:39:12Z"
  generation: 4
  labels:
    app.kubernetes.io/instance: my-juice-shop
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: juice-shop
    app.kubernetes.io/version: v12.0.2
    helm.sh/chart: juice-shop-v2.3.0
  name: my-juice-shop
  namespace: default
  resourceVersion: "514941"
  selfLink: /apis/apps/v1/namespaces/default/deployments/my-juice-shop
  uid: 4c78dcac-b5e4-4061-a15b-2793f99a39e2
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: my-juice-shop
      app.kubernetes.io/name: juice-shop
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: my-juice-shop
        app.kubernetes.io/name: juice-shop
    spec:
      containers:
      - image: docker.io/bkimminich/juice-shop:v12.0.2
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: juice-shop
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}

